# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.2"

# Relative path where 'shared-content' can be found
sharedContentRelativePath = '../shared-content'

require 'json'

# Load scenario data configuration file
scenario = JSON.parse(File.read(File.join(File.dirname(__FILE__), 'scenario.json')))
vals = scenario['config']['servers'][0]

# Vagrant intialization
Vagrant.configure("2") do |config|

    config.vm.define vals["name"]
    config.vm.box = vals["box"]

    config.vm.network "private_network", ip: vals["ip"]
    config.vm.hostname = vals["name"]

    # Virtual Machine details
    config.vm.provider :virtualbox do |v, override|
        v.name = vals["name"]
        v.linked_clone = true
        v.customize ["modifyvm", :id, "--memory", vals["memory"]]
        v.customize ["modifyvm", :id, "--cpus", vals["cpus"]]
        v.customize ["modifyvm", :id, "--vram", 99]
        v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]

    end

    # Shared synced folders setup (Host <-> Guest)
    config.vm.synced_folder "./files", "c:/installation/"
    config.vm.synced_folder sharedContentRelativePath, "c:/shared-content/"

    # Provision scripts execution
    config.vm.provision :shell, path: sharedContentRelativePath + "/scripts/modules/q-bootstrap.ps1", :powershell_elevated_interactive => true
    config.vm.provision :shell, path: "./scripts/provisioner.ps1"

end
